### ISSUE TITLE
Feature request: Optional role-ping on alt match with cheating ban

### ISSUE THREAD

**Issue by vemodsvals** [HDProduction010/SquadJS-Alt-Checker-Revamped#1]
First off, loving the plugin, works great and the additions really help. 

One request from our team would be an optional role-ping if an alt match has a cheating ban instead of automagically banning them. We've had a couple of matches of cheaters where it's been confirmed that the IP was shared through either a VPN or internet café, so we're not using the automagic ban feature for now. A ping would be great! <3

**Comment by realhddev** [comment]
Merged and updated.

Please see Releases for more info.
